[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sbscraper"
version = "0.1.0"
description = "Scrape all the things"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdfplumber>=0.11.7",
    "playwright>=1.53.0",
]

[project.optional-dependencies]
build = [
    "pyinstaller>=6.0",
]

[tool.setuptools]
py-modules = ["main", "report_by_id", "fuel_tank_report", "coord_from_id", "sb_login", "sb_config", "sb_ui"]
